### ISSUE TITLE
Invalid redirection after login

### ISSUE THREAD

**Issue by garanda21** [arikchakma/mly.fyi#30]
After a apparently successful login (some debug shows that the front is receiving the login token), the page redirect to the login page instead to go to the web UI:

https://github.com/arikchakma/mly.fyi/assets/9530250/464a794a-1e0b-4e72-9bbd-fdf6606be7fc

No errors on console or on container logs.

**Comment by arikchakma** [comment]
That's strange, It should reload and redirect. Can you give me a repro version?

**Comment by arikchakma** [comment]
Can you join me on a quick call and let me show you? I have to see your network tab or you can use https://jam.dev/ maybe to create the issue.

**Comment by arikchakma** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#secure

**Comment by arikchakma** [comment]
Sure thing🥂
